- project:
    post:
      jobs:
        - openstack-tox-cover
    templates:
      - openstack-python-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-python35-jobs
      - lib-forward-testing
      - release-notes-jobs-python3
      - periodic-stable-jobs
